[@b.grid items=writers var="writer"]
  [@b.row]
    [@b.boxcol/]
    [@b.col property="std.code"  title="学号" width="100px"/]
    [@b.col property="std.name"  title="姓名" width="130px"/]
    [@b.col property="std.state.department.name"  title="院系" width="140px"/]
    [@b.col property="std.state.major.name"  title="专业 方向 班级" ]
      ${writer.std.state.major.name} ${(writer.std.state.direction.name)!} ${(writer.std.state.squad.name)!}
    [/@]
    [@b.col property="thesisTitle" title="题目"/]
    [@b.col property="advisor.teacher.name" title="指导老师" width="100px"/]
    [@b.col property="advisor.teacher.office.name" title="指导老师教研室" width="150px"/]
  [/@]
[/@]
