  [@b.form name="exportForm" action="!exportData" target="_blank" style="text-align: center;"]
    <h5 style="display: inline;">[#if depart??]${depart.name} [/#if]${fromSeason.name}[#if toSeason.id!=fromSeason.id]~${toSeason.name}[/#if]毕业论文教师指导篇数统计表 </h5>
    [#list Parameters?keys as key]
      [#if key!='method']<input type="hidden" name="${key}" value="${Parameters[key]}" />[/#if]
    [/#list]
    <input type="hidden" name="titles" value="season.graduateIn:毕业年份,advisor.teacher.staff.code:工号,advisor.teacher.name:姓名,advisor.teacher.staff.gender.name:性别,advisor.teacher.staff.title.name:职称,advisor.teacher.department.name:院系,count:篇数"/>
    [@b.submit value="导出" class="btn btn-primary btn-sm"/]
  [/@]
  [@b.grid items=stats var="stat" style="border:0.5px solid #006CB2"]
    [@b.row]
      [@b.col width="80px" title="序号"]${stat_index+1}[/@]
      [@b.col property="season.graduateIn" title="毕业年份" width="80px"/]
      [@b.col property="advisor.teacher.staff.code" title="工号" width="80px" style="mso-number-format:'\\@';"/]
      [@b.col property="advisor.teacher.name" title="姓名" width="100px"]
        [@b.a href="!writers?advisorId="+stat.advisor.id target="_blank"]${stat.advisor.teacher.name}[/@]
      [/@]
      [@b.col property="advisor.teacher.staff.gender.name" title="性别" width="100px"/]
      [@b.col property="advisor.teacher.staff.title.name" title="职称" width="150px"/]
      [@b.col property="advisor.teacher.department.name" title="院系"/]
      [@b.col property="count" title="篇数" width="100px"]
        <span x:str>${stat.count}</span>
      [/@]
    [/@]
  [/@]
