[@b.head/]
  [@b.toolbar title="修改总体工作计划"]
    bar.addBack();
  [/@]
  [#include "stage_descriptions.ftl"/]
  [#assign times={}/]
  [#list plan.times as time]
    [#assign times = times+{time.stage.id?string:time}/]
  [/#list]
  [@b.form action=b.rest.save(plan) theme="list"]
    [@b.field label="毕业界别"]
      ${plan.season.name}
    [/@]
    [#list stages as stage]
      [#if stage.id==17][#continue/][/#if]
      [#if stage.subCount=0]
      [#if times[stage.id?string]??]
        [#assign time = times[stage.id?string]/]
        [@b.startend required="true" label=stage.name name="${stage.id}_beginOn,${stage.id}_endOn" start=time.beginOn end=time.endOn/]
      [#else]
        [@b.startend required="true" label=stage.name name="${stage.id}_beginOn,${stage.id}_endOn"/]
      [/#if]
      [/#if]
    [/#list]
    [@b.formfoot]
      <input name="plan.season.id" type="hidden" value="${(plan.season.id)!}"/>
      [@b.submit value="提交"/]
      [@b.reset/]
    [/@]
  [/@]
[@b.foot/]
