[#include "/org/openurp/degree/thesis/web/action/head.ftl"/]

<div class="container-fluid">
[@b.messages slash="3"/]
[@b.form name="indexForm" action="!index"]
  [@b.select items=thesisPlans label="毕业界别" name="plan.thesisPlan.id" value=curThesisPlan option=r"${item.season.name}" style="width:200px"/]
  [@b.submit value="查询"/]
[/@]
[#list plans as plan]
      [@b.card class="card-info card-primary card-outline"]
        [#assign title]<i class="fas fa-file-pdf"></i> ${plan.department.name}毕业论文(设计)工作计划 -- ${plan.status}[/#assign]
        [@b.card_header class="border-transparent" title=title ]
          [@b.card_tools]
            [@b.a href='!edit?id='+plan.id class="btn btn-sm btn-primary"]修改[/@]
            [@b.a href='!submit?id='+plan.id class="btn btn-sm btn-primary"]提交审查[/@]
            <a href="${b.url('!print?id='+plan.id)}" class="btn btn-sm btn-primary" target="_blank">打印</a>
          [/@]
        [/@]
        [@b.card_body class="p-0"]
          [#include "../plan/planInfoTable.ftl"/]
        [/@]
      [/@]
[/#list]
[@b.foot/]
