[@b.head/]
[@b.toolbar title='未提交论文学生明细${writers.totalItems}名']
[/@]
[@b.grid items=writers var="writer"]
  [@b.gridbar]
    bar.addItem("补充上传",action.single("uploadForm"));
  [/@]
  [@b.row]
    [@b.boxcol/]
    [@b.col property="std.code"  title="学号" width="100px"/]
    [@b.col property="std.name"  title="姓名" width="130px"/]
    [@b.col property="std.state.department.name" width="120px"  title="院系" /]
    [@b.col property="std.state.major.name"  title="专业 方向 班级" ]
      ${writer.std.state.major.name} ${(writer.std.state.direction.name)!} ${(writer.std.state.squad.name)!}
    [/@]
    [@b.col property="thesisTitle" title="题目"/]
    [@b.col property="advisor.teacher.name" title="指导老师" width="100px"/]
    [@b.col property="mobile" title="联系手机" width="120px"/]
  [/@]
[/@]
[@b.foot/]
