[@b.head/]
[#assign artifacts ={'paper':'论文'} /]
[#assign artifactName=artifacts[Parameters['absence']]/]
[@b.toolbar title='未提交${artifactName}学生明细${writers.totalItems}名']
[/@]
[@b.grid items=writers var="writer"]
  [@b.gridbar]
    bar.addItem("上传论文",action.single("uploadPaper"));
    bar.addItem("导出",action.exportData("std.code:学号,std.name:姓名,std.gender.name:性别,std.state.grade.name:年级,std.level.name:层次,std.state.department.name:院系,std.state.major.name:专业,std.state.direction.name:专业方向,std.state.squad.name:班级,mobile:手机,advisor.teacher.name:指导教师",null,'fileName=学生信息'));
  [/@]
  [@b.row]
    [@b.boxcol/]
    [@b.col property="std.code"  title="学号" width="100px"/]
    [@b.col property="std.name"  title="姓名" width="130px"/]
    [@b.col property="std.state.department.name" width="120px"  title="院系" /]
    [@b.col property="std.state.major.name"  title="专业 方向 班级" ]
      ${writer.std.state.major.name} ${(writer.std.state.direction.name)!} ${(writer.std.state.squad.name)!}
    [/@]
    [@b.col property="thesisTitle" title="题目"/]
    [@b.col property="advisor.teacher.name" title="指导老师" width="100px"/]
    [@b.col property="mobile" title="联系手机" width="120px"/]
  [/@]
[/@]
[@b.foot/]
