[@b.head/]
[@b.toolbar title="增加学生"]bar.addBack();[/@]
[@b.form name="newStdForm" action=b.rest.save(writer) theme="list"]
  [@b.select name="user.id" label="学号" required="true" href=ems.api("/base/users.json?q={term}&isStd=1")
             option="id,description" width="300px" empty="..."/]
  [@b.select name="writer.season.id" label="毕业界别" required="true" items=seasons width="200px"/]
  [@b.textfield label="指导老师工号" name="advisor_code" value=""/]
  [@b.textfield label="手机" name="writer.mobile"/]
  [@b.email label="电子邮箱" name="writer.email"/]
  [@b.formfoot]
    [@b.submit value="增加"/]
  [/@]
[/@]
[@b.foot/]
