[#ftl]
[@b.head/]
[@b.toolbar title="修改课程性质"]bar.addBack();[/@]
  [@b.form action=b.rest.save(thesisDocType) theme="list"]
    [@b.textfield name="thesisDocType.code" label="代码" value="${thesisDocType.code!}" required="true" maxlength="20"/]
    [@b.textfield name="thesisDocType.name" label="名称" value="${thesisDocType.name!}" required="true" maxlength="20"/]
    [@b.textfield name="thesisDocType.idx" label="排序" value=thesisDocType.idx required="true" maxlength="20"/]
    [@b.select name="thesisDocType.stage" label="阶段" value=(thesisDocType.stage.id)! items=stages required="true"/]
    [@b.textfield name="thesisDocType.maxSize" label="文件大小上限" value=thesisDocType.maxSize! maxlength="100" comment="MB"/]
    [@b.textfield name="thesisDocType.extensions" label="文件扩展名" value=thesisDocType.extensions! maxlength="100" comment="例如：pdf,docx,doc"/]
    [@b.startend label="有效期"
      name="thesisDocType.beginOn,thesisDocType.endOn" required="true,false"
      start=thesisDocType.beginOn end=thesisDocType.endOn format="date"/]
    [@b.textfield name="thesisDocType.remark" label="备注" value="${thesisDocType.remark!}" maxlength="300" style="width:300px"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
