[@b.head/]
[@b.toolbar title="修改评阅信息"]bar.addBack();[/@]
[@b.form name="reviewForm" action=b.rest.save(thesisReview) theme="list"]
  [@b.field label="学生"]${thesisReview.writer.std.code} ${thesisReview.writer.std.name} ${thesisReview.writer.std.state.department.name}[/@]
  [@b.select label="评阅教师" name="thesisReview.crossReviewer.id" items=crossReviewers value=thesisReview.crossReviewer! option=r"${item.description}" /]
  [@b.formfoot]
    [@b.submit value="保存"/]
  [/@]
[/@]
[@b.foot/]
