[@b.grid items=writers var="writer"]
  [@b.row]
    [@b.boxcol/]
    [@b.col property="std.code"  title="学号" width="100px"/]
    [@b.col property="std.name"  title="姓名" width="130px"/]
    [@b.col property="std.state.major.name"  title="专业 方向 班级" ]
      ${writer.std.state.major.name} ${(writer.std.state.direction.name)!} ${(writer.std.state.squad.name)!}
    [/@]
    [@b.col property="thesisTitle" title="题目"/]
    [@b.col property="advisor.teacher.name" title="指导老师" width="100px"/]
    [@b.col title="指导记录" width="150px"]
      [#if stats.get(writer.id)??]
        [#list stats.get(writer.id)?sort_by('id') as stage]
        [@b.a target="_blank" href="!view?writerId="+writer.id+"&stageId="+stage.id]${stage}[/@][#if stage_has_next]<br>[/#if]
        [/#list]
      [/#if]
    [/@]
  [/@]
[/@]
