[@b.head/]
[@b.toolbar title="修改反抄袭检测信息"]bar.addBack();[/@]
[@b.form name="copyCheckForm" action=b.rest.save(copyCheck) theme="list"]
  [@b.field label="学生"]${copyCheck.writer.std.code} ${copyCheck.writer.std.name} ${copyCheck.writer.std.state.department.name}[/@]
  [@b.radios label="是否通过"  name="copyCheck.passed" value=copyCheck.passed items="1:common.yes,0:common.no" required="true"/]
  [@b.textfield label="去除引用文献复制比" name="copyCheck.copyRatio" value=copyCheck.copyRatio! comment="类似0.002格式"/]
  [@b.textfield label="总字数" name="copyCheck.wordCount" value=copyCheck.wordCount!/]
  [@b.date label="检测日期" name="copyCheck.checkOn" value=copyCheck.checkOn required="true"/]
  [@b.radios label="是否复检"  name="copyCheck.recheck" value=copyCheck.recheck items="1:common.yes,0:common.no" required="true"/]
  [@b.formfoot]
    [@b.submit value="保存"/]
  [/@]
[/@]
[@b.foot/]
