[@b.head/]
[@b.form action="!batchAudit" theme="list"]
  [@b.field label="学生"]
    [#list checks as check]${check.writer.std.name}[#sep],[#else]没有学生，无法审核[/#list]
  [/@]
  [@b.radios label="是否通过"  name="passed" value='1' items="1:common.yes,0:common.no" required="true"/]
  [@b.textarea label="不通过原因" name="conclusion" maxlength="300" cols="80" rows="5"/]
  [@b.formfoot]
    [#if checks?size>0]
    [#list checks as c]
    <input type="hidden" name="midtermCheck.id" value="${c.id}" />
    [/#list]
    [@b.reset/] &nbsp;[@b.submit value="提交"/]
    [/#if]
  [/@]
[/@]
